### ISSUE TITLE
测试用例以测试类的形式执行时，显示不出具体用例名称，统一都显示了测试类的名称

### ISSUE THREAD

**Issue by lixintester** [five3/PyTestReport#1]
![报告截图](https://user-images.githubusercontent.com/54020911/63481187-47951780-c4c7-11e9-9655-a17aa1ba9ed0.jpg)
您好，我的测试用例是以类形式执行的，执行后显示不出具体的case名称，而是统一显示的测试类名，如上截图所示

**Comment by five3** [comment]
这个你看下测试用例方法的头部是不是有注释，如果有的话改成不一样的。这个地方的名字默认会先取文档注释。
如果没有文档注释的话，可以发一下简单的样例代码，我复现下看看

**Comment by lixintester** [comment]
> 这个你看下测试用例方法的头部是不是有注释，如果有的话改成不一样的。这个地方的名字默认会先取文档注释。
> 如果没有文档注释的话，可以发一下简单的样例代码，我复现下看看

嗯嗯 我这边写了个简单的demo试了下，没加注释，以类形式执行的话，最终报告也还是都显示的类名
demo如下：
import pytest

class TestSample(object):

    def test_A(self):
        a = 1
        b = 2
        c = a + b
        assert c == 4

    def test_B(self):
        a = 1
        b = 2
        c = a + b
        assert c == 5

    def test_C(self):
        a = 1
        b = 2
        c = a + b
        assert c == 3


if __name__ == '__main__':
    pytest.main(["-s", "pytest test_sample.py", "--pytest_report", "Pytest_Report.html"])
![截图报告](https://user-images.githubusercontent.com/54020911/63484160-5385d700-c4d1-11e9-922e-572e7c8fb9fa.jpg)

**Comment by five3** [comment]
PyTestReport 0.1.9.3版本已修复。
通过pip install -U PyTestReport 更新版本
